CREATE TABLE validations (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             collecte_id BIGINT NOT NULL REFERENCES collectes(id),
                             supervisor_id BIGINT NOT NULL REFERENCES users(id),
                             decision VARCHAR(255) NOT NULL CHECK (decision IN ('VALIDEE', 'REJETEE')),
                             comment TEXT,
                             created_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_validations_collecte_id ON validations(collecte_id);