CREATE TABLE sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL REFERENCES users(id),
    collecte_id BIGINT REFERENCES collectes(id),
    local_reference VARCHAR(255) NOT NULL,
    result VARCHAR(255) NOT NULL CHECK (result IN ('SUCCESS', 'ERROR', 'DUPLICATE')),
    error_message TEXT,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_sync_logs_agent_id ON sync_logs(agent_id);
