CREATE TABLE missions (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          description TEXT,
                          organization_id BIGINT NOT NULL REFERENCES organizations(id),
                          status VARCHAR(255) NOT NULL CHECK (status IN ('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED')),
                          start_date TIMESTAMP(6),
                          end_date TIMESTAMP(6),
                          latitude DOUBLE PRECISION,
                          longitude DOUBLE PRECISION,
                          radius_meters DOUBLE PRECISION,
                          created_by BIGINT NOT NULL REFERENCES users(id),
                          created_at TIMESTAMP(6) NOT NULL,
                          updated_at TIMESTAMP(6)
);

CREATE INDEX idx_missions_organization_id ON missions(organization_id);
CREATE INDEX idx_missions_status ON missions(status);

CREATE TABLE mission_forms (
                               mission_id BIGINT NOT NULL REFERENCES missions(id),
                               form_id BIGINT NOT NULL REFERENCES forms(id),
                               PRIMARY KEY (mission_id, form_id)
);

CREATE TABLE mission_agents (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                mission_id BIGINT NOT NULL REFERENCES missions(id),
                                agent_id BIGINT NOT NULL REFERENCES users(id),
                                assigned_at TIMESTAMP(6) NOT NULL,
                                CONSTRAINT uk_mission_agents_mission_agent UNIQUE (mission_id, agent_id)
);

CREATE INDEX idx_mission_agents_mission_id ON mission_agents(mission_id);
CREATE INDEX idx_mission_agents_agent_id ON mission_agents(agent_id);

ALTER TABLE collectes ADD COLUMN mission_id BIGINT REFERENCES missions(id);

CREATE INDEX idx_collectes_mission_id ON collectes(mission_id);