-- Logo de l'organisation, optionnel (utilisé en en-tête des rapports PDF).
ALTER TABLE organizations ADD COLUMN logo_url VARCHAR(500);

-- Historique des rapports générés (organisation ou mission).
CREATE TABLE reports (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         organization_id BIGINT NOT NULL REFERENCES organizations(id),
                         mission_id BIGINT REFERENCES missions(id),
                         type VARCHAR(50) NOT NULL CHECK (type IN ('ORGANIZATION', 'MISSION')),
                         file_path VARCHAR(500) NOT NULL,
                         generated_by BIGINT NOT NULL REFERENCES users(id),
                         generated_at TIMESTAMP(6) NOT NULL,
                         period_start TIMESTAMP(6),
                         period_end TIMESTAMP(6)
);

CREATE INDEX idx_reports_organization_id ON reports(organization_id);
CREATE INDEX idx_reports_mission_id ON reports(mission_id);

-- Garde-fou : un rapport MISSION doit avoir mission_id, un rapport ORGANIZATION non.
ALTER TABLE reports ADD CONSTRAINT chk_report_mission_consistency
    CHECK (
        (type = 'MISSION' AND mission_id IS NOT NULL) OR
        (type = 'ORGANIZATION' AND mission_id IS NULL)
        );