package com.collectpro.backend.enums;

public enum AuditAction {
    ADMIN_CREATED,
    USER_CREATED,
    USER_DISABLED,
    USER_REACTIVATED,
    FORM_PUBLISHED,
    FORM_ARCHIVED,
    COLLECTE_VALIDATED,
    COLLECTE_REJECTED,
    COLLECTE_RESUBMITTED,
    ORGANIZATION_CREATED,
    ORGANIZATION_UPDATED,
    ROLE_CHANGED,
    INVITATION_SENT,
    INVITATION_RESENT,
    ACCOUNT_ACTIVATED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    SUPERVISOR_ASSIGNED,
    MISSION_CREATED,
    MISSION_UPDATED,
    MISSION_CANCELLED,
    AGENTS_ASSIGNED_TO_MISSION,
    AGENT_UNASSIGNED_FROM_MISSION,
    FORMS_ASSIGNED_TO_MISSION,
    REPORT_GENERATED
}
