package com.collectpro.backend.enums;

public enum AuditAction {
    ADMIN_CREATED,
    USER_CREATED,
    USER_DISABLED,
    FORM_PUBLISHED,
    COLLECTE_VALIDATED,
    COLLECTE_REJECTED,
    ORGANIZATION_CREATED,
    ORGANIZATION_UPDATED,
    ROLE_CHANGED,
    INVITATION_SENT,
    INVITATION_RESENT,
    ACCOUNT_ACTIVATED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    SUPERVISOR_ASSIGNED
}
